name: 'Obsfucate Lua file'
description: 'Obsfucates the specified lua file using luraph'
inputs:
  inputFile:
    description: 'Path to Input File to Obsfucate'
    required: true
  outputFile:
    description: 'Path to Output File'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.inputFile }}
    - ${{ inputs.outputFile }}
